ResearchRes = {
    RESEARCH_DATA: "您的支持是我们的动力，你的宝贵意见是我们的改进的方向!",
    RESEARCH_FAIL: "调查填写失败！",
    RESEARCH_ERROR: "系统在忙，请稍后再试！",
    EMPTY_ERROR: "意见调查内容不能为空！",
    NUMBER_ERROR: "内容不能超过200字！"
};
TrafficRes={TRAFFIC_FLUX:"流量包",TRAFFIC_ADDITION:"加油包",TRAFFIC_DERESTRICT:"随意玩",TRAFFIC_QUERY:"流量截止:",TRAFFIC_TOTAL:"总流量",
TRAFFIC_LEAVE:"剩余流量",TRAFFIC_USE:"已用流量",TRAFFIC_TOTAL_USE:"累计用量",TRAFFIC_DESCRIBE:"流量数据仅供参考",NOT_OPEN_PACKAGE_DESCRIBE:"<div>无法获取流量数据</div>",PACKAGE_GET:"<div>正在获取<br /> 流量数据</div>",
TARFFIC_DETAILS_LINK:"流量详情",FREE_RESOURCE:"流量套餐名",PACKAGE_RECOMMED:"推荐套餐",PACKAGE_RECOMMED_DEALWITH:"流量推荐与办理",PACKAGE_FLUX_DESCRIBE:"超出部分0.001元/KB；15G流量内500元封顶。",
PACKAGE_ADDITION_DESCRIBE:"当您本月流量套餐不够用时，可开通流量叠加包，开通立即生效，月底自动关闭，每月最多可累计开通20次，及时补充您的上网流量。",PACKAGE_DERESTRICT_DESCRIBE:"流量也包夜，每天23:00至次日8:00，享受超低的上网资费：5元包1G夜间省内流量，10元包3G夜间省内流量，2G、3G随意玩，超出套餐后0.001元/KB。",PACKAGE_NOT_OPEN:"未开通",PACKAGE_OPEN_AGAIN:"再次开通",PACKAGE_CLOSE:"关闭",OPERATION_FAIL:"操作失败",PRICE_UNIT:"元/月",PRICE_UNIT_OTHER:"元/次",TRAFFIC_WORD:"流量",MB_UNIT:"MB",MB_DETAIL:"MB",KB_UNIT:"KB",GB_UNIT:"GB",NOT_OPEN_PACKAGE_TRAFFIC:"无",USED_DETAILS:"使用详情&gt;&gt;",TRAFFIC_DETAILS:"流量详情",SUBCRIBE_PACKAGE:"已购套餐",TRAFFIC_DETAILS_TITLEA:"截止",TRAFFIC_DETAILS_TITLEB:"已用合计：",TRAFFIC_DETAILS_FIRST:"GPRS流量查询",TRAFFIC_DETAILS_SECOND:"累计用量",TRAFFIC_DETAILS_THIRD:"此流量是截止目前您的准实时收费流量合计",COLOUR_RED:"#ab1600",COLOUR_ORANGE:"#f98411",COLOUR_GREEN:"#6db312",COLOUR_RED_ORANGE_VALVE:"0.8",COLOUR_ORANGE_GREEN_VALVE:"0.5",NET_ERROR:"服务器正忙，请稍后重试。",SORRY:"抱歉！<br/>",PASSWORD_ERROR:"密码错误",PASSWORD_NULL:"密码不能为空",PLEASE_WAIT:"请稍候...",PLEASE_RELOAD:"抱歉！<br>网络繁忙无法获取。<br>点击<a>重新获取</a>",NO_TRAFFIC_WARN:"当前您未开通流量套餐，上网会产生高额流量费，推荐您开通以下流量包业务。",ERROR_CODE:"(错误码:{0})",TRAFFIC_BUSINESS:"更多套餐推荐&gt;&gt;"};
TrafficDetailsRes={NO_TRAFFIC_WARN:"当前您未开通流量套餐，上网会产生高额流量费。"};
BusinessDealWith={BUSINESS_DEAL_WITH:"业务办理",BUSINESS_NAME:"业务名称:",BUSINESS_FEESTANDARD:"资费标准:",BUSINESS_CURRENTSTATE:"当前状态:",BUSINESS_SERVER_PASSWORD:"服务密码:",BUSINESS_OK:"确认",BUSINESS_SUC:"完成",BUSINESS_CANCLE:"取消",BUSINESS_REMIND_PASSWORD:"记住密码",SERVER_PASSWORD_LENGTH:"6",BUSINESS_HELLO:"您已成功开通",BUSINESS_SEVER:"业务",BUSINESS_THANKS:"感谢您的订购！",
BUSINESS_PASSWORD:"验证码：",BUSINESS_PASSWORD_NULL:"验证码不能为空",BUSINESS_PASSWORD_ERROR:"验证码错误",BUSINESS_EFFECTIVEMODE:"生效方式:"
};